function AS = build_AS(...
    p_hat,...
    u0,...
    theta_m,...
    f_hat_l,...
    fc)

    % extract dimensions
    L = size(f_hat_l,2);
    M = size(theta_m,1);
    K = size(p_hat,2);

    % 3) Build restricted sensing matrix A_S (M x |Lambda|)        
    AS = zeros(M*L, K);        
    for iatom = 1:K            
       AS(:,iatom) = compute_atom(...
           p_hat(1,iatom),...
           p_hat(2,iatom),...
           u0,...
           theta_m,f_hat_l,fc,false); 
    end
end

