

function image_parameters = ...
    define_backprojection_grid(image_parameters)

    %% backprojection

    
    % the output of the backprojection algorithm will be 
    % [Nx x Ny] where Nx is cross-range, Ny is range
    image_parameters.Nx = round(image_parameters.x_extent ...
        / image_parameters.x_pixel_resolution);
    image_parameters.Ny = round(image_parameters.y_extent ...
        / image_parameters.y_pixel_resolution);
    
    % calculate the x and y values that define the image and
    % the pixel locations relative to the radar
    image_parameters.x_array = ...
        (-floor(image_parameters.Nx/2)...
        :ceil(image_parameters.Nx/2)-1) ...
        * image_parameters.x_pixel_resolution;

    image_parameters.y_array = ...
        (-floor(image_parameters.Ny/2)...
        :ceil(image_parameters.Ny/2)-1) ...
        * image_parameters.y_pixel_resolution;

end

