function sc = extract_scenario_parameters(...
    sc, ...
    scenarios,...
    isc,...
    options)

    sc.is_target_accelerating       = ...
        strcmp(scenarios.AngleRate(isc),'Accelerating');

    sc.is_target_maneuvering        = ...
        options.manual_maneuvering_target;

    % oversampling
    sc.is_grid_oversampled          = ...
        strcmp(scenarios.ImageFormerGridDensity(isc), 'Oversampled');

    % closely-space target scattereres
    sc.is_closely_spaced            = ...
        (strcmpi(scenarios.TargetSpacing(isc), 'close') ...
        || options.manual_close_spacing) ...
        && strcmpi(scenarios.ScattererLocations(isc), 'Off-grid');

    % target scatterers on-grid or off-grid
    sc.is_off_grid                  = ...
        strcmpi(scenarios.ScattererLocations(isc), 'Off-grid');
    sc.num_amb_having_scatterers    = ...
        scenarios.NumberOfAmbiguitiesHavingScatterers(isc);
    sc.num_amb_in_image_former      = ...
        scenarios.NumberOfAmbiguitiesInImageFormer(isc);


end

