
fprintf('-------------------------------------------\n')
%close all

show_plots  = true;
save_data   = false;
save_plots  = false;
compare_results = false;
truth_data_dir = 'data/truth_la.mat';

% define the length of the simulation
T = nan; % [s]
angular_extent = deg2rad(32); % [rad]

% define the scenario
sc = scenario_basic(T, angular_extent);

% define imaging parameters
image_parameters.x_pixel_resolution = 0.25; % [m] range
image_parameters.y_pixel_resolution = 0.25; % [m] cross-range
image_parameters.x_extent           = 20; % [m] range
image_parameters.y_extent           = 20; % [m] cross-range
image_parameters.truncate           = true;
image_parameters.truncation_margin  = 4; % [m]
image_parameters.imager             = 'standard'; % 'standard' or 'weighted'

% execute the isar imager
output = isar_imager(sc, image_parameters);


%% plotting
% plot_raw_isar(...
%     output.rx_signal, ...
%     sc.signal.range_array, ...
%     show_plots, ...
%     save_plots);
original_omega = pi;
original_omega_factor = 1/(original_omega/pi);
omega_factor = 1/(sc.target.yawing_rate/pi);
omega_dot_factor = 1/(sc.target.yawing_acceleration/pi);

if isa(sc, 'scenario_psf')
    plot_psf(...
        output.rx_signal_bp, ...
        output.x_array, ...
        output.y_array, ...
        show_plots, ...
        save_plots,...
        omega_factor, ...
        omega_dot_factor)
end

plot_backprojection_sd(...
    output.rx_signal_bp, ...
    output.x_array, ...
    output.y_array, ...
    show_plots, ...
    save_plots, ...
    num2str(omega_factor));

plot_backprojection_sfd(...
    output.rx_signal_sfd, ...
    output.kx, ...
    output.ky, ...
    show_plots, ...
    save_plots, ...
    num2str(omega_factor));

if compare_results
    
    plot_backprojection_comparison_amp_sd(...
        output.rx_signal_bp, ...
        output.x_array, ...
        output.y_array, ...
        show_plots, ...
        save_plots, ...
        omega_factor, ...
        omega_dot_factor,...
        original_omega_factor, ...
        truth_data_dir);
    
    plot_backproj_comparison_sfd(...
        output.rx_signal_sfd, ...
        output.kx, ...
        output.ky, ...
        show_plots, ...
        save_plots, ...
        omega_factor, ...
        omega_dot_factor, ...
        original_omega_factor, ...
        truth_data_dir);
    
    plot_backproj_comparison_amp_sfd(...
        output.rx_signal_sfd, ...
        output.kx, ...
        output.ky, ...
        show_plots, ...
        save_plots, ...
        omega_factor, ...
        omega_dot_factor, ...
        original_omega_factor, ...
        truth_data_dir);
end

plot_target_range_and_traj(...
    sc.signal.t_slow, ...
    output.ranges, ...
    output.scatterer_positions, ...
    sc.target.yaws, ...
    show_plots, ...
    save_plots, ...
    num2str(omega_factor));

% truth_output = load('data/backproj_analysis/truth_output.mat');
% truth_output = truth_output.output;
% 
% mse = mean(abs(truth_output.rx_signal_bp - output.rx_signal_bp), "all");

%% save data
if save_data
    save(truth_data_dir, "output");
end






