
fprintf('-------------------------------------------\n')
close all

show_plots  = true;
save_data   = true;
save_plots  = false;
truth_data_dir = 'data/truth_output_sfd_angular_samples.mat';

% define the length of the simulation
T = nan; % [s]
angular_extent = deg2rad(32); % [rad]

% define the scenario
sc = scenario_basic(T, angular_extent);

% define imaging parameters
image_parameters.x_pixel_resolution = 0.25; % [m] range
image_parameters.y_pixel_resolution = 0.25; % [m] cross-range
image_parameters.x_extent           = 20; % [m] range
image_parameters.y_extent           = 20; % [m] cross-range


% execute the isar imager
output = isar_imager(sc, image_parameters);


%% plotting
% plot_raw_isar(...
%     output.rx_signal, ...
%     sc.signal.range_array, ...
%     show_plots, ...
%     save_plots);

factor = 1/(sc.target.yawing_acceleration/pi);

plot_backprojection_sd(...
    output.rx_signal_bp, ...
    output.x_array, ...
    output.y_array, ...
    show_plots, ...
    save_plots, ...
    num2str(factor));

plot_backprojection_sfd(...
    output.rx_signal_sfd, ...
    output.kx, ...
    output.ky, ...
    show_plots, ...
    save_plots, ...
    num2str(factor));

plot_backprojection_comparison_sd(...
    output.rx_signal_bp, ...
    output.x_array, ...
    output.y_array, ...
    show_plots, ...
    save_plots, ...
    num2str(factor),...
    truth_data_dir);

plot_backproj_comparison_sfd(...
    output.rx_signal_sfd, ...
    output.kx, ...
    output.ky, ...
    show_plots, ...
    save_plots, ...
    num2str(factor), ...
    truth_data_dir);

plot_backproj_comparison_amp_sfd(...
    output.rx_signal_sfd, ...
    output.kx, ...
    output.ky, ...
    show_plots, ...
    save_plots, ...
    num2str(factor), ...
    truth_data_dir);

plot_target_range_and_traj(...
    sc.signal.t_slow, ...
    output.ranges, ...
    output.scatterer_positions, ...
    sc.target.yaws, ...
    show_plots, ...
    save_plots, ...
    num2str(factor));

% truth_output = load('data/backproj_analysis/truth_output.mat');
% truth_output = truth_output.output;
% 
% mse = mean(abs(truth_output.rx_signal_bp - output.rx_signal_bp), "all");

%% save data
if save_data
    save('data/truth_output_sfd_angular_samples.mat', "output");
end






